# Generated by Django 3.2.6 on 2021-10-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='active',
        ),
    ]
