# Generated by Django 3.2.6 on 2021-08-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210826_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='steam_link',
            new_name='steam',
        ),
    ]
